#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

uv run ruff check \
  src/ruletrade/api.py \
  src/ruletrade/backtest_runs \
  src/ruletrade/backtests \
  src/ruletrade/candidates \
  src/ruletrade/comparisons \
  src/ruletrade/compiler/__init__.py \
  src/ruletrade/compiler/analysis \
  src/ruletrade/compiler/frontend \
  src/ruletrade/compiler/lean/__init__.py \
  src/ruletrade/compiler/lean/cooldown_e2e.py \
  src/ruletrade/compiler/lean/e2e.py \
  src/ruletrade/compiler/lean/evidence_e2e.py \
  src/ruletrade/compiler/lean/fallback_e2e.py \
  src/ruletrade/compiler/lean/filter_e2e.py \
  src/ruletrade/compiler/lean/independent_schedules_e2e.py \
  src/ruletrade/compiler/lean/lowering.py \
  src/ruletrade/compiler/lean/momentum_e2e.py \
  src/ruletrade/compiler/lean/sleeves_e2e.py \
  src/ruletrade/compiler/pipeline.py \
  src/ruletrade/decision_evidence \
  src/ruletrade/diagnostics.py \
  src/ruletrade/ir \
  src/ruletrade/market_data \
  src/ruletrade/persistence \
  src/ruletrade/strategies \
  scripts/generate_golden_lean_fixture.py \
  scripts/generate_candidate_lean.py \
  scripts/generate_cooldown_lean.py \
  scripts/generate_fallback_lean.py \
  scripts/generate_filter_lean.py \
  scripts/generate_independent_schedules_lean.py \
  scripts/generate_momentum_lean.py \
  scripts/generate_sleeves_lean.py \
  scripts/generate_one_investment_lean.py \
  scripts/run_editor_lean_e2e.py \
  scripts/measure_research_pipeline.py \
  scripts/inspect_market_data.py \
  scripts/run_candidate_comparison_lean_e2e.py \
  scripts/run_lean_backtest.py \
  scripts/run_real_market_data_smoke.py \
  scripts/verify_momentum_lean_e2e.py \
  scripts/verify_cooldown_lean_e2e.py \
  scripts/verify_fallback_lean_e2e.py \
  scripts/verify_filter_lean_e2e.py \
  scripts/verify_independent_schedules_lean_e2e.py \
  scripts/verify_sleeves_lean_e2e.py \
  tests/test_api.py \
  tests/test_backtest_runs.py \
  tests/test_candidates.py \
  tests/test_comparisons.py \
  tests/test_cooldown.py \
  tests/test_decision_evidence.py \
  tests/test_fallback.py \
  tests/test_filter_screening.py \
  tests/test_independent_schedules.py \
  tests/test_lean_backtest_service.py \
  tests/test_lean_e2e_validation.py \
  tests/test_lean_result_normalization.py \
  tests/test_lean_runner.py \
  tests/test_market_data.py \
  tests/test_momentum_top_n.py \
  tests/test_portfolio_sleeves.py \
  tests/test_pipeline_observability.py \
  tests/test_strategy_ir.py \
  tests/test_strategy_ir_analysis.py \
  tests/test_strategy_ir_differential.py \
  tests/test_strategy_persistence.py
