import type { EditorBootstrap } from "../domain/canonical";
import type { StrategyExample } from "../domain/examples";
import { projectGuided } from "../domain/guided";

const percent = (value: string) => `${Math.round(Number(value) * 100)}%`;

export function ExamplePreview({ point, bootstrap, onBack, onTest, onStart, creating }: { point: StrategyExample; bootstrap: EditorBootstrap; onBack: () => void; onTest: () => void; onStart: () => void; creating?: boolean }) {
  const summary = projectGuided(bootstrap.strategy, bootstrap.registry);
  return <section className="page preview-page"><button className="text-button preview-back" onClick={onBack}>← Explore</button><header><span className="eyebrow">Example preview</span><h1>{point.question}</h1><p>{point.description}</p></header><div className="preview-summary">
    {summary.kind === "portfolio" && <><section><header><h2>{summary.growth.sleeveName}</h2><strong>{percent(summary.growth.allocation)}</strong></header><p>{summary.growth.assets.join(" · ")}</p><ol><li>Qualify assets above {percent(summary.growth.threshold ?? "0")} over {summary.growth.lookbackBars} trading days.</li><li>Choose the strongest {summary.growth.topN}.</li><li>Otherwise use {summary.growth.fallbackAsset}.</li></ol></section><section><header><h2>{summary.defensive.sleeveName}</h2><strong>{percent(summary.defensive.allocation)}</strong></header><p>{summary.defensive.assets.join(" · ")}</p><ol><li>Hold these assets alongside Growth.</li><li>Split this part equally.</li></ol></section></>}
    {summary.kind === "momentum" && <section><header><h2>Assets to consider</h2><strong>{percent(summary.momentum.total)}</strong></header><p>{summary.momentum.assets.join(" · ")}</p><ol><li>Measure {summary.momentum.lookbackBars}-day returns{summary.momentum.threshold !== undefined ? ` and qualify those above ${percent(summary.momentum.threshold)}` : ""}.</li><li>Choose the strongest {summary.momentum.topN} and split equally.</li>{summary.momentum.fallbackAsset && <li>Otherwise use {summary.momentum.fallbackAsset}.</li>}{summary.momentum.cooldownDuration && <li>Wait {summary.momentum.cooldownDuration} trading days before buying a sold asset again.</li>}</ol></section>}
    {summary.kind === "golden" && <><section><header><h2>Growth</h2><strong>{percent(summary.growth.total)}</strong></header><p>{summary.growth.assets.join(" · ")}</p><ol><li>Choose {summary.growth.randomCount} assets at each check.</li><li>Split this part equally.</li></ol></section><section><header><h2>Safety</h2><strong>{percent(summary.safe.total)}</strong></header><p>{summary.safe.assets.join(" · ")}</p><ol><li>Hold all safety assets.</li><li>Split this part equally.</li></ol></section></>}
    {summary.kind === "single" && <section><header><h2>One investment</h2><strong>{percent(summary.investment.total)}</strong></header><p>{summary.investment.assets.join(" · ")}</p><ol><li>Invest fully in this asset.</li><li>Check again {summary.investment.schedule.toLowerCase()}.</li></ol></section>}
  </div><footer><button className="secondary-button" onClick={onTest}>Test this strategy</button><button className="primary-button" disabled={creating} onClick={onStart}>{creating ? "Creating…" : "Start with this strategy"}</button></footer></section>;
}
