import { useMemo, type PointerEvent as ReactPointerEvent, type ReactNode } from "react";
import { projectConceptualFlow, type ConceptualChoose, type ConceptualGroup } from "../domain/conceptualFlow";
import { useStrategyEditor } from "../store/editorStore";
import { AssetMembershipEditor, LookbackControl, ScheduleControl, SleeveAllocationEditor } from "../components/AuthoringControls";

type Selection = { kind: "portfolio" } | { kind: "split" } | { kind: "group"; group: ConceptualGroup } | { kind: "choose"; group: ConceptualGroup; choose: ConceptualChoose };
const defaults: Record<string, { x: number; y: number }> = { "concept:portfolio": {x:310,y:35}, "concept:split":{x:325,y:165}, "concept:group:0":{x:90,y:325}, "concept:group:1":{x:500,y:325}, "concept:assets":{x:90,y:120}, "concept:choose":{x:405,y:120}, "concept:fallback":{x:430,y:350} };

export function FlowView() {
  const { state, dispatch } = useStrategyEditor();
  const projection = useMemo(() => projectConceptualFlow(state.canonical, state.registry), [state.canonical, state.registry]);
  const group = projection.groups.find((item) => item.id === state.editor.openGroupId);
  const selected = selectionFor(state.editor.selectedConceptId, group, projection.groups);
  const select = (conceptId: string, componentId?: string) => { dispatch({type:"select_concept",conceptId}); if(componentId) dispatch({type:"select_node",componentId}); };
  const move=(id:string,x:number,y:number)=>dispatch({type:"move_node",componentId:id,position:{x,y}});
  return <section className="intuitive-flow" aria-label="Visual strategy builder" onKeyDown={(e)=>{if(e.key==="Escape")dispatch({type:"select_concept",conceptId:null})}} tabIndex={-1}>
    <Library group={group}/><main className="intuitive-canvas-wrap"><nav className="concept-breadcrumb" aria-label="Strategy hierarchy"><button onClick={()=>dispatch({type:"open_group",groupId:null})}>Portfolio</button>{group&&<><span>/</span><strong>{group.label}</strong></>}</nav><div className="intuitive-canvas" onClick={(e)=>{if(e.currentTarget===e.target)dispatch({type:"select_concept",conceptId:null})}}>{group?<GroupCanvas group={group} selectedId={state.editor.selectedConceptId} positions={state.editor.nodePositions} onSelect={select} onMove={move}/>:<PortfolioCanvas groups={projection.groups} rebalance={projection.rebalance} selectedId={state.editor.selectedConceptId} positions={state.editor.nodePositions} onSelect={select} onOpen={(g)=>dispatch({type:"open_group",groupId:g.id})} onMove={move}/>}</div></main><Inspector selection={selected} projection={projection}/>
  </section>;
}

function Library({group}:{group?:ConceptualGroup}){return <aside className="object-library"><span className="eyebrow">Strategy map</span><h3>{group?group.label:"Portfolio"}</h3><p>Select an object to edit its real strategy settings.</p><div className="library-legend"><span><i className="legend-swatch split"/>Split money</span><span><i className="legend-swatch choose"/>Choose assets</span><span><i className="legend-swatch fallback"/>Otherwise</span></div><small>{group?"Assets can be added or removed in the Inspector.":"Double-click a Group to open it."}</small></aside>}

function DraggableNode({id,position,selected,onMove,onClick,onDoubleClick,children,className=""}:{id:string;position:{x:number;y:number};selected:boolean;onMove:(id:string,x:number,y:number)=>void;onClick:()=>void;onDoubleClick?:()=>void;children:ReactNode;className?:string}){function down(event:ReactPointerEvent<HTMLButtonElement>){const startX=event.clientX,startY=event.clientY,origin=position;event.currentTarget.setPointerCapture(event.pointerId);const move=(e:PointerEvent)=>onMove(id,Math.max(8,origin.x+e.clientX-startX),Math.max(8,origin.y+e.clientY-startY));const up=()=>{window.removeEventListener("pointermove",move);window.removeEventListener("pointerup",up)};window.addEventListener("pointermove",move);window.addEventListener("pointerup",up)}return <button className={`intuitive-node ${className}${selected?" selected":""}`} style={{left:position.x,top:position.y}} onPointerDown={down} onClick={e=>{e.stopPropagation();onClick()}} onDoubleClick={onDoubleClick} aria-pressed={selected}>{children}</button>}
function pos(positions:Record<string,{x:number;y:number}>,id:string,index?:number){return positions[id]??defaults[index===undefined?id:`concept:group:${index}`]??{x:80,y:80}}
function PortfolioCanvas({groups,rebalance,selectedId,positions,onSelect,onOpen,onMove}:{groups:ConceptualGroup[];rebalance?:string;selectedId:string|null;positions:Record<string,{x:number;y:number}>;onSelect:(id:string,c?:string)=>void;onOpen:(g:ConceptualGroup)=>void;onMove:(id:string,x:number,y:number)=>void}){return <><DraggableNode id="concept:portfolio" position={pos(positions,"concept:portfolio")} selected={selectedId==="portfolio"} onMove={onMove} onClick={()=>onSelect("portfolio")} className="portfolio"><strong>Portfolio</strong><span>{rebalance?`Rebalance: ${rebalance}`:"All invested money"}</span></DraggableNode><DraggableNode id="concept:split" position={pos(positions,"concept:split")} selected={selectedId==="split"} onMove={onMove} onClick={()=>onSelect("split")} className="split"><strong>Split money</strong><span>{groups.map(g=>g.allocation).filter(Boolean).join(" / ")||"Destinations"}</span></DraggableNode>{groups.map((g,i)=><DraggableNode key={g.id} id={`concept:group:${i}`} position={pos(positions,"",i)} selected={selectedId===`group:${g.id}`} onMove={onMove} onClick={()=>onSelect(`group:${g.id}`,g.sourceComponentIds[0])} onDoubleClick={()=>onOpen(g)} className="group"><strong>{g.label} {g.allocation}</strong><span>{g.choose?.label??g.assets.join(" · ")}</span>{g.timing&&<em>Re-evaluate: {g.timing}</em>}<small>Double-click to open</small></DraggableNode>)}</>}
function GroupCanvas({group,selectedId,positions,onSelect,onMove}:{group:ConceptualGroup;selectedId:string|null;positions:Record<string,{x:number;y:number}>;onSelect:(id:string,c?:string)=>void;onMove:(id:string,x:number,y:number)=>void}){return <><DraggableNode id="concept:assets" position={pos(positions,"concept:assets")} selected={selectedId===`group:${group.id}`} onMove={onMove} onClick={()=>onSelect(`group:${group.id}`,group.sourceComponentIds[0])} className="group"><strong>{group.label} assets</strong><span>{group.assets.join(" · ")}</span></DraggableNode>{group.choose&&<DraggableNode id="concept:choose" position={pos(positions,"concept:choose")} selected={selectedId==="choose"} onMove={onMove} onClick={()=>onSelect("choose",group.choose!.selectionComponentId)} className="choose"><strong>{group.choose.label}</strong>{group.choose.condition&&<span>{group.choose.condition}</span>}<span>{group.choose.ranking}</span>{group.choose.otherwise&&<em>{group.choose.otherwise}</em>}</DraggableNode>}{group.choose?.otherwise&&<DraggableNode id="concept:fallback" position={pos(positions,"concept:fallback")} selected={selectedId==="fallback"} onMove={onMove} onClick={()=>onSelect("fallback",group.choose!.fallbackComponentId)} className="fallback"><strong>{group.choose.otherwise.replace("Otherwise → ","")}</strong><span>Otherwise destination</span></DraggableNode>}</>}

function selectionFor(id:string|null,group:ConceptualGroup|undefined,groups:ConceptualGroup[]):Selection{if(id==="split")return{kind:"split"};if((id==="choose"||id==="fallback")&&group?.choose)return{kind:"choose",group,choose:group.choose};if(id?.startsWith("group:")){const found=groups.find(g=>`group:${g.id}`===id);if(found)return{kind:"group",group:found}}return{kind:"portfolio"}}
function Inspector({selection,projection}:{selection:Selection;projection:ReturnType<typeof projectConceptualFlow>}){if(selection.kind==="split"&&projection.split)return <SplitInspector groups={projection.split.groups}/>;if(selection.kind==="choose")return <ChooseInspector group={selection.group} choose={selection.choose}/>;if(selection.kind==="group")return <GroupInspector group={selection.group}/>;return <aside className="flow-inspector"><span className="eyebrow">Portfolio</span><h3>{projection.title}</h3><p>Money can go to {projection.groups.map(g=>g.label).join(" and ")}.</p>{projection.rebalanceScheduleComponentId&&<ScheduleControl label="Rebalance portfolio" componentId={projection.rebalanceScheduleComponentId} value={projection.rebalance!}/>}<small>Position, selection, and open Group are editor-only. They never change the strategy.</small></aside>}
function ChooseInspector({group,choose}:{group:ConceptualGroup;choose:ConceptualChoose}) {
  const {dispatch}=useStrategyEditor();
  return <aside className="flow-inspector"><span className="eyebrow">Choose assets</span><h3>{choose.label}</h3>
    <label>From<input value={group.label} disabled/></label>
    {choose.lookbackComponentId&&<LookbackControl id="flow-lookback" componentId={choose.lookbackComponentId} value={choose.lookbackBars!}/>}
    {choose.filterComponentId&&<label>Only include when<span className="condition-input"><b>Return is greater than</b><input aria-label="Return threshold percent" type="number" step="0.1" value={Number(choose.threshold)*100} onChange={e=>dispatch({type:"apply_semantic_patch",operation:{kind:"update_component_config",componentId:choose.filterComponentId!,field:"threshold",value:String(Number(e.target.value)/100)}})}/>%</span></label>}
    {choose.selectionMode==="ranked"?<label>Then order<input value="Strongest return first" disabled/><small>The current Rank contract supports this direction only.</small></label>:<label>How should it choose?<select value={choose.resample} onChange={e=>dispatch({type:"apply_semantic_patch",operation:{kind:"update_component_config",componentId:choose.selectionComponentId,field:"resample",value:e.target.value}})}><option value="per_event">Choose again each check</option><option value="once">Keep the first random choice</option></select></label>}
    <label>Choose<input type="number" min={1} value={choose.topN} onChange={e=>dispatch({type:"apply_semantic_patch",operation:{kind:"update_component_config",componentId:choose.selectionComponentId,field:"count",value:Number(e.target.value)}})}/></label>
    <p className="fixed-setting">Split selected assets equally</p>
    {choose.fallbackComponentId&&<label>Otherwise<select value={choose.fallbackAssetSetRef} onChange={e=>dispatch({type:"apply_semantic_patch",operation:{kind:"update_component_config",componentId:choose.fallbackComponentId!,field:"fallback_asset_set_ref",value:e.target.value}})}>{choose.fallbackOptions.map(o=><option key={o.id} value={o.id}>{o.asset}</option>)}</select></label>}
    {choose.cooldownComponentId&&<label>After selling, wait<input type="number" min={1} value={choose.cooldownDuration} onChange={e=>dispatch({type:"apply_semantic_patch",operation:{kind:"update_component_config",componentId:choose.cooldownComponentId!,field:"duration",value:Number(e.target.value)}})}/><span>completed trading days before buying again</span></label>}
    {choose.scheduleComponentId&&<ScheduleControl label="Check choices" componentId={choose.scheduleComponentId} value={choose.timing!}/>}
    <small>Every change is validated against the same strategy used by Guided.</small>
  </aside>;
}
function GroupInspector({group}:{group:ConceptualGroup}){return <aside className="flow-inspector"><span className="eyebrow">Group</span><h3>{group.label}</h3>{group.assetSetId?<AssetMembershipEditor question="Where can money go?" assetSetId={group.assetSetId} assets={group.assets}/>:<p>{group.assets.join(" · ")}</p>}{group.scheduleComponentId&&<ScheduleControl label="Check choices" componentId={group.scheduleComponentId} value={group.timing!}/>}</aside>}
function SplitInspector({groups}:{groups:Array<{id:string;label:string;componentId:string;allocation:string}>}){return <aside className="flow-inspector"><span className="eyebrow">Split money</span><h3>Portfolio allocation</h3><SleeveAllocationEditor groups={groups}/></aside>}
