import { projectGuided } from "../domain/guided";
import { tryProjectSemanticStrategy } from "../domain/semanticProjection";
import { useStrategyEditor } from "../store/editorStore";

const percent = (value: string) => `${Math.round(Number(value) * 100)}%`;

export function OverviewView({ onTest }: { onTest: () => void }) {
  const { state, dispatch } = useStrategyEditor();
  const semantic = tryProjectSemanticStrategy(state.canonical, state.registry);
  if (!semantic.supported) return <div className="overview-view"><section className="overview-story"><span className="eyebrow">Strategy overview</span><h2>This valid strategy shape is not available in the current Builder.</h2><p>{semantic.reason}</p></section></div>;
  const semanticPortfolio = semantic.projection.kind === "portfolio" && semantic.projection.portfolioComponentId
    ? semantic.projection : null;
  if (semanticPortfolio && !semanticPortfolio.groups.some((group) => group.pipeline.selectionMode === "ranked" && group.pipeline.selectionComponentId)) {
    return <div className="overview-view"><section className="overview-story"><span className="eyebrow">This strategy</span><h2>Split the portfolio across two investment groups</h2><ol>{semanticPortfolio.groups.map((group) => <li key={group.id}>Keeps {percent(group.allocation)} in {group.name}: {group.pipeline.assets.join(", ")}.</li>)}</ol></section><section className="quick-settings"><header><span className="eyebrow">At a glance</span><h2>Current allocations</h2></header>{semanticPortfolio.groups.map((group) => <div key={group.id}><span>{group.name}</span><strong>{percent(group.allocation)}</strong></div>)}<footer><button className="secondary-button" onClick={() => dispatch({ type: "set_active_view", view: "guided" })}>Customize</button><button className="primary-button" onClick={onTest}>Test</button></footer></section></div>;
  }
  const guided = projectGuided(state.canonical, state.registry);
  const customize = () => dispatch({ type: "set_active_view", view: "guided" });

  if (guided.kind === "single") return <div className="overview-view"><section className="overview-story"><span className="eyebrow">This strategy</span><h2>Hold one investment</h2><ol><li>Invests in {guided.investment.assets.join(", ")}.</li><li>Uses {percent(guided.investment.total)} of the portfolio.</li><li>Checks the allocation {guided.investment.schedule.toLowerCase()}.</li></ol></section><section className="quick-settings"><header><span className="eyebrow">At a glance</span><h2>Current assumptions</h2></header><div><span>Investment</span><strong>{guided.investment.assets.join(", ")}</strong></div><div><span>Allocation</span><strong>{percent(guided.investment.total)}</strong></div><footer><button className="secondary-button" onClick={customize}>Customize</button><button className="primary-button" onClick={onTest}>Test</button></footer></section></div>;

  if (guided.kind === "portfolio") return <div className="overview-view"><section className="overview-story"><span className="eyebrow">This strategy</span><h2>{guided.growth.sleeveName} when conditions are strong, {guided.defensive.sleeveName.toLowerCase()} alongside it</h2><ol><li>Looks at {guided.growth.assets.join(", ")} for {guided.growth.sleeveName}.</li><li>Keeps assets whose {guided.growth.lookbackBars}-day return is above {percent(guided.growth.threshold ?? "0")}.</li><li>Chooses the strongest {guided.growth.topN} and splits {guided.growth.sleeveName} equally.</li><li>Uses {guided.growth.fallbackAsset} when the primary selection is incomplete.</li><li>Keeps {percent(guided.defensive.allocation)} in {guided.defensive.assets.join(" and ")}.</li></ol></section><section className="quick-settings" aria-label="Quick settings"><header><span className="eyebrow">Quick settings</span><h2>Key assumptions</h2></header>{guided.growth.filterComponentId && <div><span>Return threshold</span><strong>{percent(guided.growth.threshold ?? "0")}</strong></div>}<div><span>Number selected</span><strong>{guided.growth.topN}</strong></div><div><span>Fallback</span><strong>{guided.growth.fallbackAsset}</strong></div><div><span>{guided.growth.sleeveName} / {guided.defensive.sleeveName}</span><strong>{percent(guided.growth.allocation)} / {percent(guided.defensive.allocation)}</strong></div><div><span>Checks again</span><strong>{guided.growth.refreshSchedule ?? guided.rebalanceSchedule}</strong></div><footer><button className="secondary-button" onClick={customize}>Customize</button><button className="primary-button" onClick={onTest}>Test</button></footer></section></div>;

  if (guided.kind === "momentum") return <div className="overview-view"><section className="overview-story"><span className="eyebrow">This strategy</span><h2>Choose assets with the strongest recent returns</h2><ol><li>Looks at {guided.momentum.assets.join(", ")}.</li><li>Measures each asset over {guided.momentum.lookbackBars} trading days.</li>{guided.momentum.threshold !== undefined && <li>Keeps assets above {percent(guided.momentum.threshold)}.</li>}<li>Chooses the strongest {guided.momentum.topN} and splits the money equally.</li>{guided.momentum.fallbackAsset && <li>Uses {guided.momentum.fallbackAsset} when the primary selection is incomplete.</li>}{guided.momentum.cooldownDuration && <li>After selling, waits {guided.momentum.cooldownDuration} completed trading days before buying again.</li>}</ol></section><section className="quick-settings"><header><span className="eyebrow">At a glance</span><h2>Current assumptions</h2></header><div><span>Recent history</span><strong>{guided.momentum.lookbackBars} trading days</strong></div><div><span>Number selected</span><strong>{guided.momentum.topN}</strong></div><div><span>Checks again</span><strong>{guided.momentum.schedule}</strong></div><footer><button className="secondary-button" onClick={customize}>Customize</button><button className="primary-button" onClick={onTest}>Test</button></footer></section></div>;

  return <div className="overview-view"><section className="overview-story"><span className="eyebrow">This strategy</span><h2>Mix a changing Growth sleeve with a steady Safety sleeve</h2><ol><li>Growth considers {guided.growth.assets.join(", ")}.</li><li>It randomly selects {guided.growth.randomCount} at each decision.</li><li>Safety holds {guided.safe.assets.join(" and ")}.</li><li>Each sleeve splits its allocation equally.</li></ol></section><section className="quick-settings"><header><span className="eyebrow">At a glance</span><h2>Current assumptions</h2></header><div><span>Growth allocation</span><strong>{percent(guided.growth.total)}</strong></div><div><span>Safety allocation</span><strong>{percent(guided.safe.total)}</strong></div><footer><button className="secondary-button" onClick={customize}>Customize</button><button className="primary-button" onClick={onTest}>Test</button></footer></section></div>;
}
