import { projectGuided } from "../domain/guided";
import { useStrategyEditor } from "../store/editorStore";

const percent = (value: string) => `${Math.round(Number(value) * 100)}%`;

export function OverviewView({ onTest }: { onTest: () => void }) {
  const { state, dispatch } = useStrategyEditor();
  const guided = projectGuided(state.canonical, state.registry);
  const customize = () => dispatch({ type: "set_active_view", view: "guided" });

  if (guided.kind === "single") return <div className="overview-view"><section className="overview-story"><span className="eyebrow">This strategy</span><h2>Hold one investment</h2><ol><li>Invests in {guided.investment.assets.join(", ")}.</li><li>Uses {percent(guided.investment.total)} of the portfolio.</li><li>Checks the allocation {guided.investment.schedule.toLowerCase()}.</li></ol></section><section className="quick-settings"><header><span className="eyebrow">At a glance</span><h2>Current assumptions</h2></header><div><span>Investment</span><strong>{guided.investment.assets.join(", ")}</strong></div><div><span>Allocation</span><strong>{percent(guided.investment.total)}</strong></div><footer><button className="secondary-button" onClick={customize}>Customize</button><button className="primary-button" onClick={onTest}>Test</button></footer></section></div>;

  if (guided.kind === "portfolio") return <div className="overview-view"><section className="overview-story"><span className="eyebrow">This strategy</span><h2>{guided.growth.sleeveName} when conditions are strong, {guided.defensive.sleeveName.toLowerCase()} alongside it</h2><ol><li>Looks at {guided.growth.assets.join(", ")} for {guided.growth.sleeveName}.</li><li>Keeps assets whose {guided.growth.lookbackBars}-day return is above {percent(guided.growth.threshold ?? "0")}.</li><li>Chooses the strongest {guided.growth.topN} and splits {guided.growth.sleeveName} equally.</li><li>Uses {guided.growth.fallbackAsset} when the primary selection is incomplete.</li><li>Keeps {percent(guided.defensive.allocation)} in {guided.defensive.assets.join(" and ")}.</li></ol></section><section className="quick-settings" aria-label="Quick settings"><header><span className="eyebrow">Quick settings</span><h2>Key assumptions</h2></header>{guided.growth.filterComponentId && <label>Return threshold<span><input aria-label="Return threshold percent" type="number" step="0.1" value={Number(guided.growth.threshold ?? 0) * 100} onChange={(event) => { if (event.target.value !== "") dispatch({ type: "apply_semantic_patch", operation: { kind: "update_component_config", componentId: guided.growth.filterComponentId!, field: "threshold", value: String(Number(event.target.value) / 100) } }); }} />%</span></label>}<label>Number selected<input aria-label="Number selected" type="number" min={1} max={guided.growth.assets.length} value={guided.growth.topN} onChange={(event) => dispatch({ type: "apply_semantic_patch", operation: { kind: "update_component_config", componentId: guided.growth.selectionComponentId, field: "count", value: Number(event.target.value) } })} /></label><div><span>Fallback</span><strong>{guided.growth.fallbackAsset}</strong></div><div><span>{guided.growth.sleeveName} / {guided.defensive.sleeveName}</span><strong>{percent(guided.growth.allocation)} / {percent(guided.defensive.allocation)}</strong></div><div><span>Checks again</span><strong>{guided.growth.refreshSchedule ?? guided.rebalanceSchedule}</strong></div><footer><button className="secondary-button" onClick={customize}>Customize</button><button className="primary-button" onClick={onTest}>Test</button></footer></section></div>;

  if (guided.kind === "momentum") return <div className="overview-view"><section className="overview-story"><span className="eyebrow">This strategy</span><h2>Choose assets with the strongest recent returns</h2><ol><li>Looks at {guided.momentum.assets.join(", ")}.</li><li>Measures each asset over {guided.momentum.lookbackBars} trading days.</li>{guided.momentum.threshold !== undefined && <li>Keeps assets above {percent(guided.momentum.threshold)}.</li>}<li>Chooses the strongest {guided.momentum.topN} and splits the money equally.</li>{guided.momentum.fallbackAsset && <li>Uses {guided.momentum.fallbackAsset} when the primary selection is incomplete.</li>}{guided.momentum.cooldownDuration && <li>After selling, waits {guided.momentum.cooldownDuration} completed trading days before buying again.</li>}</ol></section><section className="quick-settings"><header><span className="eyebrow">At a glance</span><h2>Current assumptions</h2></header><div><span>Recent history</span><strong>{guided.momentum.lookbackBars} trading days</strong></div><div><span>Number selected</span><strong>{guided.momentum.topN}</strong></div><div><span>Checks again</span><strong>{guided.momentum.schedule}</strong></div><footer><button className="secondary-button" onClick={customize}>Customize</button><button className="primary-button" onClick={onTest}>Test</button></footer></section></div>;

  return <div className="overview-view"><section className="overview-story"><span className="eyebrow">This strategy</span><h2>Mix a changing Growth sleeve with a steady Safety sleeve</h2><ol><li>Growth considers {guided.growth.assets.join(", ")}.</li><li>It randomly selects {guided.growth.randomCount} at each decision.</li><li>Safety holds {guided.safe.assets.join(" and ")}.</li><li>Each sleeve splits its allocation equally.</li></ol></section><section className="quick-settings"><header><span className="eyebrow">At a glance</span><h2>Current assumptions</h2></header><div><span>Growth allocation</span><strong>{percent(guided.growth.total)}</strong></div><div><span>Safety allocation</span><strong>{percent(guided.safe.total)}</strong></div><footer><button className="secondary-button" onClick={customize}>Customize</button><button className="primary-button" onClick={onTest}>Test</button></footer></section></div>;
}
